# application.yml - ОЧИЩЕНИЕ ОТ ДУБЛИРУЮЩИХСЯ НАСТРОЕК
spring:
  application:
    name: bank-rest

  profiles:
    active: dev

---
# Настройки для разработки (профиль dev)
spring:
  config:
    activate:
      on-profile: dev
  web:
    resources:
      cache:
        period: 0  # Отключаем кэширование ресурсов (предотвращает фоновые запросы)

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Важно: не используем create-drop, чтобы Liquibase полностью контролировал схему
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        # изменил ИИ: УДАЛЕНО - naming strategy настроен в JpaConfig.java, избегаем дублирования
        # naming:
        #   physical_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        #   implicit_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Настройки для Swagger/OpenAPI
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    # чтобы Swagger показывал кнопку "Authorize":
    security-schemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        description: 'JWT токен: Bearer <токен>'

# Настройки JWT
jwt:
  secret: 6d9a8f4c2b7e1a3d5f8c9b2a7e4d1f6c3a9b8d7e2f5c1a3d6f9e8b7c4a2d5f1e3c # Минимум 32 символа для HS256
  expiration: 86400000 # Время жизни токена в миллисекундах (24 часа)

# Настройки логирования для удобства отладки
logging:
  level:
    com.example.bank_rest: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false  # Отключаем secure cookies для HTTP
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto